### ISSUE TITLE
Workaround to test on insecure env

### ISSUE THREAD

**Issue by lashchanka** [bahmutov/cypress-data-session#24]
If env is insecure:
![image](https://user-images.githubusercontent.com/81577230/141155004-6e0646c3-4aaf-440b-9f81-9fed05b4ba1b.png)

This error is thrown:
```
// Browsers throw if they lack support for an algorithm.
  16 |   // Promise will be rejected on non-secure origins. (http://goo.gl/lq4gCo)
```  

![image](https://user-images.githubusercontent.com/81577230/141155234-8ea6f2fc-da96-49b8-aca8-7c088a1dbab6.png)

How could I proceed?

Cypress: v8.7.0
Node.js: v16

**Comment by bahmutov** [comment]
How did you get this? It works on my test sites

**Comment by bahmutov** [comment]
Ok, this might happen during testing an external HTTP site, especially during https -> HTTP -> https redirect
<img width="770" alt="Screen Shot 2021-12-02 at 09 44 27" src="https://user-images.githubusercontent.com/2212006/144444334-ad3b78e9-8518-4f88-9321-60658a169a8a.png">
