### ISSUE TITLE
after init(), it does not run validate() OR presetup() & setup()

### ISSUE THREAD

**Issue by muratkeremozcan** [bahmutov/cypress-data-session#27]
This issue is much easier to explain with a state chart. Please take a look at the chart at https://github.com/muratkeremozcan/cypress-data-session-statechart

The problem is on the left path:
* Assume there is no cached value
* We run init()
* After init(), neither of the paths execute; validate() does not run OR presetup() & setup do not run.

Minimal repro:
```js
git clone https://github.com/muratkeremozcan/cypress-data-session-statechart.git
cd cypress-data-session-statechart
npm i
npm cy:open
```
Focus on the spec `left-path-no-cache.spec.js`.  

Observe that the test `Left Path: Existing user / init() returns true: should run init() validate()` does not run validate().

Enable the 2nd test `Right Path: init() returns false: should run init() preSetup() setup()`. Observe that it fails because it does not run preSetup() & setup() to create a new user.

**Comment by bahmutov** [comment]
Ughh, the code vs chart is not matching. I am looking at the "init" tests in init.js and in particular at https://github.com/bahmutov/cypress-data-session/blob/88a099b5a27b1b977468b4846fe1aa4aa9c8a8fb/cypress/integration/init.js#L55-L75

It says "if the init returns a value, validate is not called", which to me seems like a mistake - we want to validate the value too. I will change it to call "validate"
