### ISSUE TITLE
`experimentalSessionSupport` breaks `shareAcrossSpecs`

### ISSUE THREAD

**Issue by IanVS** [bahmutov/cypress-data-session#36]
It took me a long time of scratching my head to realize that my specs were recomputing and failing because `shareAcrossSpecs` was not working correctly, due to having `experimentalSessionSupport` enabled, which clears the Cypress.env before each test, while cypress-data-session relies on that cache to store the results.

I think it would be good to throw a clear error if it's detected that `experimentalSessionSupport` is enabled and `shareAcrossSpecs` is set as well.

**Comment by IanVS** [comment]
Maybe this is not quite true, I see in the code that `Cypress.env()` is not used for `shareAcrossSpecs`, but it is used to determine whether to recompute.  I can't figure out why, but running the tests a second time is not finding anything in Cypress.env(), which causes them to recompute and fail...

**Comment by IanVS** [comment]
OK, I think I see.  I was trying out a hard reload, which I saw you do in one of your videos.  This does seem to clear out `Cypress.env()`, which forces `setup()` to run again.  Is that intentional, or maybe a bug?

**Comment by bahmutov** [comment]
Hard reload is same as loading a different spec and should load the value from the plug-in space. If it does not, it’s a bug

**Comment by IanVS** [comment]
I think it does load the saved value, but not the timestamp that is saved into `Cypress.env()`.  So, since it cannot find a timestamp, it runs `setup()` again, which in my case causes an error if it has already run.

**Comment by bahmutov** [comment]
Ohh could be!

**Comment by bahmutov** [comment]
Hey @IanVS can you create a simple reproducible example showing the problem? I have checked the spec https://github.com/bahmutov/cypress-data-session/blob/main/cypress/integration/dependent-shared.js that has shared value with a dependent session, and that does have the timestamps correctly handled.

**Comment by IanVS** [comment]
I don't have any dependent sessions.  I'll try to make a test, though.  👍

**Comment by IanVS** [comment]
I've opened https://github.com/bahmutov/cypress-data-session/pull/37 with an example of what I'm seeing.

**Comment by IanVS** [comment]
Great, my tests are passing now with the new version.  Thanks for the fix!
