### ISSUE TITLE
regression in version 1.13.4 with dependent sessions

### ISSUE THREAD

**Issue by muratkeremozcan** [bahmutov/cypress-data-session#39]
Happens if a data session depends on a parent session.

Reproducing sample repo PR: https://github.com/muratkeremozcan/cypress-data-session-user-auth-example/pull/8. To make it fail, we only added a parent session to the main one.

```
git clone https://github.com/muratkeremozcan/cypress-data-session-user-auth-example.git
git checkout test/new-data-session-13.4
npm i
npm run cy:open
```

This is related to the issue addressed in https://github.com/bahmutov/cypress-data-session/issues/36.

**Comment by bahmutov** [comment]
Is this what you are getting? Because you are trying to create data session "userSession-cache" which depends on the data session "getTokenResponse" - which I do not see you creating anywhere!

<img width="488" alt="Screen Shot 2021-12-16 at 11 53 41" src="https://user-images.githubusercontent.com/2212006/146414473-70d3c672-edda-4a68-99a8-abbda8250a21.png">

**Comment by muratkeremozcan** [comment]
> Is this what you are getting? Because you are trying to create data session "userSession-cache" which depends on the data session "getTokenResponse" - which I do not see you creating anywhere!
> 
> <img alt="Screen Shot 2021-12-16 at 11 53 41" width="488" src="https://user-images.githubusercontent.com/2212006/146414473-70d3c672-edda-4a68-99a8-abbda8250a21.png">

Apologies. I pushed another commit and kept it much simpler. Please try again.

Run once. Close the runner. Run again.

**Comment by bahmutov** [comment]
This is what you get, right? "foo" is valid, yet "adminSession" cannot find it
<img width="592" alt="Screen Shot 2021-12-16 at 15 24 33" src="https://user-images.githubusercontent.com/2212006/146443998-e22a53dd-84c3-492a-bf20-c0a55a2bddce.png">

**Comment by bahmutov** [comment]
This fixed the reproduction example @muratkeremozcan
